site_name: Erdos.jl
site_author: Carlo Lucibello
repo_url: https://github.com/CarloLucibello/Erdos.jl/
docs_dir: 'build'

theme: readthedocs

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

pages:
  - 'Getting Started': 'index.md'
  - 'Graph Types': 'graph_types.md'
  - 'Basic Interface': 'core.md'
  - 'Network Types': 'network_types.md'
  - 'Maps': 'maps.md'
  - 'Operators': 'operators.md'
  - 'Traversals': 'traversals.md'
  - 'Distance': 'distance.md'
  - 'Shortest Paths': 'shortestpaths.md'
  - 'Linear Algebra': 'linalg.md'
  - 'Reading / Writing Graphs': 'persistence.md'
  - 'Graph Datasets': 'datasets.md'
  - 'Deterministic Graphs': 'deterministicgraphs.md'
  - 'Random Graphs': 'randomgraphs.md'
  - 'Centrality Measures': 'centrality.md'
  - 'Community Structures': 'community.md'
  - 'Flow and Cut': 'flow.md'
  - 'Matching': 'matching.md'
  - 'Dismantling': 'dismantling.md'
  - 'Spanning Trees': 'spanningtrees.md'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
